name: Test A
on:
  workflow_dispatch:
  push:
    paths:
      - 'testA/**'
    branches: [main]
env:
  REMOTE_REPO: "https://${{ secrets.GHCR_TOKEN }}:@github.com/hashilbasheer/argocd-test.git"

jobs:
  deployment:
    runs-on: ubuntu-latest
  
    name: Update Helm Chart    
    steps:
      - name: Clone Manifest Repository
        run: | 
          pwd
          ls -la
          git clone -b main ${REMOTE_REPO}
          ls -la
      - name: Get Short sha
        run: |
          echo "SHORT_SHA=$(echo ${{ github.sha }} |cut -c1-7)" >> $GITHUB_ENV
      - name: Update Image Version in the HelmChart values.yaml
        id: deployment
        run: |
          npm install -g yq
          yq e ".images.tag = \"$SHORT_SHA\"" -i manifest/values.yaml
          git config --global user.name "hashilbasheer"
          git config --global user.email "hashilbasheer@gmail.com"
          git add manifest/values.yaml
          git commit -m " image tag changed to '$SHORT_SHA'  "
          git push origin main    
