name: Test A
on:
  workflow_dispatch:
  push:
    paths:
      - 'testA/**'
    branches: [main]
permissions:
  id-token: write
  contents: write
  actions: write    
jobs:
  deployment:
    runs-on: ubuntu-latest
  
    name: Update Helm Chart    
    steps:
      - name: Clone Deployment Repo
        uses: actions/checkout@master
        with:
          repository: hashilbasheer/argocd-test
          token: ${{ secrets.GHCR_TOKEN }}
      
      - name: Get Short sha
        run: |
          echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
      
      - name: Update Image Version in the HelmChart values.yaml
        run: |
          npm install -g yq
          yq e ".imagesA.tag = \"$SHORT_SHA\"" -i manifest/values.yaml
          git config --global user.name "hashilbasheer"
          git config --global user.email "testr@gmail.com"
          git add manifest/values.yaml
          git commit -m "image tag changed to '$SHORT_SHA'"
          
          # Retry logic for pushing changes
          success=0;
          attempts=0;
          until $success || [ $attempts = 10 ];
          do
             let ++attempts;
             git pull --rebase;
             git push;
             success=$?;
          done;
          if ! $success;
          then
              echo "Gave up after $attempts attempts";
          fi
