name: Test D
on:
  workflow_dispatch:
  push:
    paths:
      - 'testD/**'
    branches: [main]
permissions:
  id-token: write
  contents: write
  actions: write
jobs:
  deployment:
    runs-on: ubuntu-latest
  
    name: Update Helm Chart    
    steps:
      - name: Clone Deployment Repo
        uses: actions/checkout@master
        with:
          repository: hashilbasheer/argocd-test
          token: ${{ secrets.GHCR_TOKEN }}

      - name: Get Short sha
        run: |
          echo "SHORT_SHA=$(echo ${{ github.sha }} |cut -c1-7)" >> $GITHUB_ENV

      - name: Update Image Version in the HelmChart values.yaml
        run: |
          # Define the retry parameters
          MAX_RETRIES=10
          RETRY_DELAY=15
          
          # Install yq and update the image version
          npm install -g yq
          yq e ".imagesD.tag = \"$SHORT_SHA\"" -i manifest/values.yaml
          
          # Configure git
          git config --global user.name "hashilbasheer"
          git config --global user.email "testr@gmail.com"
          
          # Add and commit the changes
          git add manifest/values.yaml
          git commit -m "image tag changed to '$SHORT_SHA'"
          
          # Retry function to push changes with retries
          chmod +x ./scripts/retry_push.sh
          ./scripts/retry_push.sh
